#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
#
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := inner_product.asm

# header files in this project
HEADERS := lib.hpp

# other places to look for files for this project
SEARCH  :=

# other files to create
RESULTS :=

# set REATIVE to the next higher directory
# and defer to the Makefile.due there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
